import esbuild from "esbuild";
import process from "process";
import fs from "fs/promises";
import path from "path";

const isProd = process.argv.includes("--prod");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's github repository
*/
`;

const buildOptions = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    // Node 내장 모듈 (데스크톱 전용 플러그인 — 렌더러에서 require 가능)
    "https",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  target: "es2020",
  platform: "browser",
  logLevel: "info",
  sourcemap: isProd ? false : "inline",
  treeShaking: true,
  minify: isProd,
  outfile: "dist/main.js",
  jsx: "automatic",
};

async function copyStaticAssets() {
  await fs.mkdir("dist", { recursive: true });
  await fs.copyFile("manifest.json", "dist/manifest.json");
  // styles.css는 T-004에서 추가된다. 없어도 build는 통과시킨다.
  try {
    await fs.copyFile("src/styles/built.css", "dist/styles.css");
  } catch {
    // not built yet
  }
}

if (isProd) {
  await esbuild.build(buildOptions);
  await copyStaticAssets();
  console.log("Production build complete");
  process.exit(0);
} else {
  const ctx = await esbuild.context(buildOptions);
  await copyStaticAssets();
  await ctx.watch();
  console.log("Watching for changes...");
}
